[workspace]
members = ["macros", "macros-core", "macros2", "macros2-core"]

[package]
name = "drone-core"
version = "0.8.0" # remember to update html_root_url
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
description = "Drone is a Hard Real-Time Operating System Framework."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/drone-os/drone-core"

[features]
default = []
std = ['futures/use_std']

[dependencies.drone-core-macros]
version = "0.8.0"
path = "macros"

[dependencies.drone-core-macros2]
version = "0.8.0"
path = "macros2"

[dependencies.futures]
version = "0.1"
default-features = false

[dependencies.clippy]
version = "0.0"
optional = true

[dev-dependencies]
glob = "0.2"

[dev-dependencies.compiletest_rs]
version = "0.3"
features = ["tmp"]
