[workspace]
members = ["ctypes", "macros", "macros-core"]

[package]
name = "drone-core"
version = "0.8.1" # remember to update html_root_url
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
description = "Drone is a Hard Real-Time Operating System Framework."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/drone-os/drone-core"

[features]
default = []
std = ['futures/std']

[dependencies.drone-ctypes]
version = "0.8.1"
path = "ctypes"

[dependencies.drone-core-macros]
version = "0.8.1"
path = "macros"

[dependencies.futures]
version = "0.2"
default-features = false

[dependencies.failure]
version = "0.1"
default-features = false

[dependencies.failure_derive]
version = "0.1"
default-features = false

[dependencies.clippy]
version = "0.0"
optional = true

[dev-dependencies]
glob = "0.2"

[dev-dependencies.compiletest_rs]
version = "0.3"
features = ["tmp"]

[profile.dev]
incremental = false

[profile.test]
incremental = false
