[workspace]
members = ["macros"]

[package]
name = "drone"
version = "0.7.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
description = "Drone is a Hard Real-Time Operating System Framework."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/drone-os/drone"

[features]
default = []
std = []

[dependencies.drone-macros]
version = "0.7.0"
path = "macros"

[dependencies.futures]
version = "0.1"
default-features = false

[dependencies.clippy]
version = "0.0"
optional = true

[dev-dependencies]
glob = "0.2"

[dev-dependencies.compiletest_rs]
version = "0.3"
features = ["tmp"]
