[workspace]
members = ["ctypes", "macros", "macros-core"]

[package]
name = "drone-core"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
description = "The platform-independent foundation of Drone OS."
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/drone-os/drone-core"

[features]
default = []
std = ["futures-preview/std"]

[dependencies.drone-ctypes]
version = "=0.9.0"
path = "ctypes"

[dependencies.drone-core-macros]
version = "=0.9.0"
path = "macros"

[dependencies]
futures-preview = { version = "0.3.0-alpha", default-features = false }
