[package]
name = "drone-macros-core"
version = "0.10.2"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
repository = "https://github.com/drone-os/drone-core"
homepage = "https://www.drone-os.com/"
documentation = "https://api.drone-os.com/drone-core/0.10/drone_macros_core/"
license = "MIT OR Apache-2.0"
description = """
Procedural macros base for Drone, an Embedded Operating System.
"""

[dependencies]
lazy_static = "1"
proc-macro2 = { version = "0.4", features = ["nightly"] }
quote = "0.6"
regex = "1"
syn = { version = "0.15", features = ["extra-traits"] }
