[package]
name = "drone-macros-core"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
description = "Drone procedural macros shared lib."
license = "MIT OR Apache-2.0"
repository = "https://github.com/drone-os/drone-core"

[dependencies]
lazy_static = "1"
proc-macro2 = { version = "0.4", features = ["nightly"] }
regex = "1"
syn = { version = "0.15", features = ["extra-traits"] }
quote = "0.6"
