[package]
name = "drone-macros-core"
version = "0.7.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
description = "Drone procedural macros shared lib."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/drone-os/drone"

[dependencies]
failure = "0.1"
lazy_static = "1"
quote = "0.3"
regex = "0.2"

[dependencies.syn]
version = "0.11"
features = ["full", "parsing", "printing"]

[dependencies.clippy]
version = "0.0"
optional = true
