[package]
name = "test"
version = "0.1.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
sc = "0.2"
clippy = {version = "*", optional = true}

[features]
panic_item = []
default = []

[lib]
