[package]
name = "drone-core-macros"
version = "0.8.1" # remember to update html_root_url
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
description = "Drone procedural macros."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/drone-os/drone-core"

[lib]
proc-macro = true

[dependencies]
if_chain = "0.1"
Inflector = "0.11"
proc-macro2 = { version = "0.3", features = ["nightly"] }
quote = "0.5"

[dependencies.syn]
version = "0.13"
features = ["full"]

[dependencies.drone-macros-core]
version = "0.8.1"
path = "../macros-core"
